apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitwarden
  namespace: argocd
spec:
  project: default
  source:
    # Manifests
    - repoURL: git@github.com:nghminh163/gitops.git
      targetRevision: main
      path: apps/vaultwarden/manifests
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: vaultwarden
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
