apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://jellyfin.github.io/jellyfin-helm
      chart: jellyfin
      targetRevision: "*"
      helm:
        valueFiles:
          - values.yaml

    - repoURL: git@github.com:nghminh163/gitops.git
      targetRevision: main
      path: apps/jellyfin/manifests
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: jellyfin

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
