apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin-nfs-provisioner
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
    chart: nfs-subdir-external-provisioner
    targetRevision: "*"
    helm:
      values: |
        nfs:
          server: 192.168.1.55
          path: /volume1/media

        storageClass:
          name: jellyfin-media
          reclaimPolicy: Retain
          accessModes: ReadWriteMany

  destination:
    server: https://kubernetes.default.svc
    namespace: jellyfin

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
