apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-provisioner
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
    chart: nfs-subdir-external-provisioner
    targetRevision: 4.0.18
    helm:
      values: |
        nfs:
          server: 192.168.1.55
          path: /volume1/homelab
          mountOptions:
            - nfsvers=4.1
        storageClass:
          create: true
          name: nfs-homelab
          defaultClass: false
          pathPattern: "${.PVC.namespace}/${.PVC.name}"
          onDelete: retain
          archiveOnDelete: false
  destination:
    server: https://kubernetes.default.svc
    namespace: nfs-provisioner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
