apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whoami
  namespace: argocd
spec:
  project: default
  sources:
    # Helm chart
    - repoURL: https://cowboysysop.github.io/charts
      chart: whoami
      targetRevision: 6.0.0
      helm:
        valueFiles:
          - values.yaml
    # Manifests
    - repoURL: git@github.com:nghminh163/gitops.git
      targetRevision: main
      path: apps/whoami/manifests
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: whoami
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
