apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bloodhound
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://github.com/SpecterOps/BloodHound.git
      targetRevision: main
      path: examples/helm
      helm:
        releaseName: bloodhound-ce
        valueFiles:
          - $values/apps/bloodhound/values.yaml

    - repoURL: git@github.com:nghminh163/gitops.git
      targetRevision: main
      path: apps/bloodhound/manifests
      directory:
        recurse: true
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: bloodhound

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
