apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: torrent
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:nghminh163/gitops.git
    targetRevision: main
    path: apps/torrent/manifests
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: torrent
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
