apiVersion: v1
kind: Service
metadata:
  name: graph-db
  namespace: bloodhound
spec:
  selector:
    app: bloodhound
    component: neo4j
  ports:
    - name: bolt
      port: 7687
      targetPort: 7687
    - name: http
      port: 7474
      targetPort: 7474
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: graph-db
  namespace: bloodhound
spec:
  serviceName: graph-db
  replicas: 1
  selector:
    matchLabels:
      app: bloodhound
      component: neo4j
  template:
    metadata:
      labels:
        app: bloodhound
        component: neo4j
    spec:
      containers:
        - name: neo4j
          image: neo4j:4.4.42
          ports:
            - containerPort: 7687
              name: bolt
            - containerPort: 7474
              name: http
          env:
            - name: NEO4J_AUTH
              value: "neo4j/$(NEO4J_SECRET)"
            - name: NEO4J_SECRET
              valueFrom:
                secretKeyRef:
                  name: bloodhound-secrets
                  key: NEO4J_SECRET
            - name: NEO4J_dbms_allow__upgrade
              value: "true"
          volumeMounts:
            - name: neo4j-data
              mountPath: /data
          readinessProbe:
            httpGet:
              path: /
              port: 7474
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 12
          livenessProbe:
            httpGet:
              path: /
              port: 7474
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 6
  volumeClaimTemplates:
    - metadata:
        name: neo4j-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 20Gi
