apiVersion: v1
kind: Service
metadata:
  name: bloodhound
  namespace: bloodhound
spec:
  selector:
    app: bloodhound
    component: bloodhound
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bloodhound
  namespace: bloodhound
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bloodhound
      component: bloodhound
  template:
    metadata:
      labels:
        app: bloodhound
        component: bloodhound
    spec:
      containers:
        - name: bloodhound
          image: specterops/bloodhound:latest
          ports:
            - containerPort: 8080
              name: http
          env:
            # Theo compose mẫu :contentReference[oaicite:5]{index=5}
            - name: bhe_disable_cypher_complexity_limit
              value: "false"
            - name: bhe_enable_cypher_mutations
              value: "false"
            - name: bhe_graph_query_memory_limit
              value: "2"
            - name: bhe_recreate_default_admin
              value: "false"
            - name: bhe_graph_driver
              value: "neo4j"

            # Connection strings (compose mẫu dùng format này) :contentReference[oaicite:6]{index=6}
            - name: bhe_database_connection
              value: "user=bloodhound password=$(POSTGRES_PASSWORD) dbname=bloodhound host=app-db sslmode=disable"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bloodhound-secrets
                  key: POSTGRES_PASSWORD

            - name: bhe_neo4j_connection
              value: "neo4j://neo4j:$(NEO4J_SECRET)@graph-db:7687/"
            - name: NEO4J_SECRET
              valueFrom:
                secretKeyRef:
                  name: bloodhound-secrets
                  key: NEO4J_SECRET

          readinessProbe:
            httpGet:
              path: /system/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 12
          livenessProbe:
            httpGet:
              path: /system/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 6
